-- Copyright (c) 2026 Jianchao Yang
-- Licensed under the MIT License - see the LICENSE file for details.

local M = {}

-- Begining and ending tag for the preview block.
M.BEGIN_TAG = '/// --- [MLIR_INC_PREVIEW_START] ---'
M.END_TAG = '/// --- [MLIR_INC_PREVIEW_END] ---'

-- Leading / trailing markers used to comment out the original include line.
M.BEGIN_COMMENT_LINE = '/// '
M.END_COMMENT_LINE = " /// <- GENERATED BY MLIR INC PREVIEWER! DON'T EDIT!"

-- How many lines to search for an include line from the current line (upwards
-- and downwards).
M.SEARCH_INC_LINE_RANGE = 3

-- When expanding in macro-aware mode, drop the content of conditional blocks
-- that are not active given the macro state of the host file.
M.REMOVE_UNRELATED_PREVIEW_BLOCKS = true

-- Default user options. Overridable through `require('mlir-inc-previewer').setup{}`.
M.defaults = {
  -- File extensions (without the leading dot) the plugin attaches keymaps and
  -- clean-on-save to. Matches the C/C++/CUDA family supported by the original
  -- VS Code extension, independent of Neovim's filetype detection.
  extensions = {
    -- Standard
    'c', 'cpp', 'cxx', 'h', 'hpp', 'hxx',
    -- Variants
    'cc', 'cp', 'c++', 'hh', 'hp', 'h++',
    -- Inline / template
    'inl', 'inc', 'ipp', 'tcc', 'tpp',
    -- Definitions
    'def',
    -- CUDA
    'cu', 'cuh',
  },
  -- Expanded preview blocks are never written to disk: clean them on :write.
  clean_on_save = true,
  -- Use the LSP (e.g. clangd) to resolve the real path of the .inc file.
  -- The LSP is only queried if an attached server actually supports
  -- `textDocument/definition`, so no error is shown when none does.
  use_lsp = true,
  -- How many lines above/below the cursor to look for an include line.
  search_range = 3,
  -- Allow a recursive project-tree search as a last-resort path resolver.
  -- Disable on very large repos if the fallback is slow (rely on the LSP).
  deep_search = true,
  -- In macro-aware mode, insert a one-line /// comment summarising each
  -- contiguous region of omitted (inactive) code. Ignored when hide_inactive_blocks
  -- is true.
  omit_marker = true,
  -- When true, drop entire inactive #if..#endif blocks (directives, markers, and
  -- body). Only active conditional content is shown.
  hide_inactive_blocks = false,
  -- Buffer-local keymaps. Set any entry to false/'' to disable it.
  keymaps = {
    toggle = '<leader>iu',          -- Expand/Collapse (macro-aware)
    toggle_full = '<leader>ij',     -- Expand/Collapse (macro-unaware)
    expand_all = '<leader>iy',      -- Expand all (macro-aware)
    expand_all_full = '<leader>ih', -- Expand all (macro-unaware)
    clean = '<leader>ic',           -- Clean all preview blocks
    next = '<leader>in',            -- Navigate to next preview block
  },
}

-- Active options (mutated by setup()).
M.options = vim.deepcopy(M.defaults)

return M
